"""empty message

Revision ID: 15bf8b0a8e88
Revises: 69c97fdd438c
Create Date: 2018-07-09 20:09:29.440075

"""

# revision identifiers, used by Alembic.
revision = '15bf8b0a8e88'
down_revision = '69c97fdd438c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
