"""empty message

Revision ID: 69c97fdd438c
Revises: 3c1542929556
Create Date: 2018-06-26 20:56:51.704188

"""

# revision identifiers, used by Alembic.
revision = '69c97fdd438c'
down_revision = '3c1542929556'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeclock_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['timeclock_id'], ['timeclocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timeclock_id'), 'comments', ['timeclock_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_timeclock_id'), table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
