"""empty message

Revision ID: 8ceee2d53a54
Revises: 15bf8b0a8e88
Create Date: 2018-07-23 15:38:49.731011

"""

# revision identifiers, used by Alembic.
revision = '8ceee2d53a54'
down_revision = '15bf8b0a8e88'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.add_column('timeclocks', sa.Column('comment', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeclocks', 'comment')
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('timeclock_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['timeclock_id'], [u'timeclocks.id'], name=u'comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
